#!/bin/bash

if [ `whoami` != "root" ]; then
    echo "$0 must be run as root"
    exit 1
fi

# target: Backup-Ziel
# ignore: Liste zu ignorierender Datenbanken (durch | getrennt)
# conf: MySQL Config-Datei, welche die Zugangsdaten enthaelt
target=/root/backup-mysql
ignore="phpmyadmin|mysql|information_schema|performance_schema|test"
conf=/etc/mysql/leuwer.cnf
log=/usr/bin/logger

$log "$0 - Dumping of MYSQL databases started."

if [ ! -r $conf ]; then
    $log "$0 - cannot access $conf."
    exit 1
fi

if [ ! -d $target ] || [ ! -w $target ]; then
    $log "$0 - cannot write to backup dir."
    exit 1
fi

databases="$(/usr/bin/mysql --defaults-extra-file=$conf -Bse 'show databases' | /bin/grep -Ev $ignore)"
now=$(date +"%Y-%m-%d")

# Dump the data databases into SQL command files.
for db in $databases; do
    echo "   dumping $db ..."
    /usr/bin/mysqldump --defaults-extra-file=$conf --skip-extended-insert --skip-comments $db > $target/$db.sql
done

$log "$0 - DUMPING of MYSQL databases  finished."
exit 0
